---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Pre-Commit run
    uses: mighty-muffin/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: mighty-muffin/.github/.github/workflows/reusable-secret.yml@main

    secrets: inherit

  sast:
    needs:
      - pre-commit
    name: Placeholder - SAST
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run SAST
        run: echo Static Application Security Testing
        shell: bash

  sca:
    needs:
      - pre-commit
    name: Placeholder - SCA
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash

  unit-test:
    needs:
      - secret
      - sca
      - sast
    name: Run Unit Tests & Integration Tests
    uses: mighty-muffin/.github/.github/workflows/reusable-python-uv.yml@main

    with:
      python_version: "3.13"
      ruff_version: "0.12.10"
      uv_version: "0.8.13"
      working_directory: .

  docker-build-push:
    needs:
      - unit-test
    name: Call Docker Build
    uses: mighty-muffin/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      platforms: |
          linux/amd64
          linux/arm64

  release:
    needs:
      - docker-build-push
    name: Version - Release bump
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    if: "!startsWith(github.event.head_commit.message, 'bump:')"

    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.RELEASE_PAT }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.13

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@5b0848cd060263e24602d1eba03710e056ef7711 # 0.24.0
        with:
          github_token: ${{ secrets.RELEASE_PAT }}
          branch: main
