# File: .github/workflows/release.yml
on:
  push:
    branches:
      - main

jobs:

  bump:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ secrets.RELEASE_PAT }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.13

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.24.0
        with:
          github_token: ${{ secrets.RELEASE_PAT }}
          branch: main
