---
name: CI - Tag

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

concurrency:
  group: tag-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      notes: ${{ steps.generate_notes.outputs.notes }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.13

      - name: Get version from tag
        id: tag_name
        run: |
          echo "{current_version}=${GITHUB_REF#refs/tags/v}" >> $GITHUB_STATE
        shell: bash

      - name: Get notes
        id: generate_notes
        uses: anmarkoulis/commitizen-changelog-reader@v1.2.0
        with:
          tag_name: ${{ github.ref }}
          changelog: CHANGELOG.md

      - name: Create Release Notes File
        run: |
          echo "${{join(fromJson(steps.generate_notes.outputs.notes).notes, '')}}" > ${{ github.workspace }}-GH_CHANGELOG.md

      - name: GH Release
        uses: softprops/action-gh-release@v2.3.3
        if: github.ref_type == 'tag'
        with:
          body_path: ${{ github.workspace }}-GH_CHANGELOG.md
          repository: ${{ github.repository }}
          token: ${{ secrets.RELEASE_PAT }}
